### ISSUE TITLE
Beautiful theme! could it be used in ArkOS?

### ISSUE THREAD

**Issue by ChestnutHeng** [anthonycaccese/art-book-next-es#13]

**Comment by anthonycaccese** [comment]
Thank you, this version of the theme only works with distributions that use the latest Batocera (v39 and above) fork of EmulationStation. Specifically [Batocera](https://batocera.org/), [Knulli](https://www.knulli.org/) and [RetroBat](https://www.retrobat.org/).  ArkOS uses a different fork of ES which is not compatible.
