### ISSUE TITLE
Double titles 

### ISSUE THREAD

**Issue by Aletroid** [anthonycaccese/art-book-next-es#14]
I’m having an issue where the text or title of the consoles is “doubled”? I’ve tried changing the configurations but it still shows the “double” text. 
device: anbernic rg35xx plus
![IMG_0239](https://github.com/anthonycaccese/art-book-next-es/assets/89193130/80127c07-94eb-49ef-8cf9-5b1a4829fc9e)
![IMG_0242](https://github.com/anthonycaccese/art-book-next-es/assets/89193130/5cb2c8ad-2e75-4de5-ad77-82c40e36d295)
![IMG_0240](https://github.com/anthonycaccese/art-book-next-es/assets/89193130/b3a24b2f-e76d-4a0b-9fe5-e63f6c4445a3)

**Comment by anthonycaccese** [comment]
what version of batocera ES does your distribution use?  If its less that v40 then some of my changes may not work (like the conditional that is added for titles)

**Comment by anthonycaccese** [comment]
will close this for now based on my note above - but if you are using v40 and still seeing this issue please let me know

**Comment by thebrodi** [comment]
I have the same problem. But I'm using batocera-h5-rg35xx-plus-39-20240213?

**Comment by anthonycaccese** [comment]
please upgrade to v40 - the theme requires features of that version to work properly
