### ISSUE TITLE
1:1 screen issues

### ISSUE THREAD

**Issue by Kurosawa79** [anthonycaccese/art-book-next-es#15]
When using this theme in Android ES-DE on my Zpg A1 Unicorn which has a 1:1 screen, the bottom row of button legends don't all  fit on the screen and runs off the edges. I think if the font could be made smaller it would fit

**Comment by anthonycaccese** [comment]
i'll relook at the helpsystem after this feature is implemented in ES-DE: https://gitlab.com/es-de/emulationstation-de/-/issues/1336

without that feature; on smaller screens there will always be some text cutoff i'm afraid.   and changing the text size will unfortunately make it harder to read for screens that don't have the same resolution as the ZPG a1 unicorn.   

For now you can try turning off some of the help icons like setting `Random Entry Button = Disabled` and `Enable toggle favorites button = off` (both in UI settings).  

Thank you for writing will close this for now
