### ISSUE TITLE
Oled

### ISSUE THREAD

**Issue by M2ljay** [anthonycaccese/art-book-next-es#19]
When selecting oled a lot of the theme is still gray which defeats the purpose of an oled theme, can the gray elements be changed to black?

**Comment by anthonycaccese** [comment]
the 000000 color is applied to the right side of the theme when OLED is selected (which is typically 111111).  I could look at trying different colors but may be a bit of time till i can try it out.  For now if you are interested please check out the instructions on creating a custom color scheme.
