### ISSUE TITLE
Are you using custom Skraper mixes?

### ISSUE THREAD

**Issue by luminarious** [anthonycaccese/art-book-next-es#21]
Hey, this theme looks excellent but I can't seem to figure out how to have the screenshot + logo image. Are you using a custom image mix, or is Knulli on Trimui Smart Pro just lacking some options?

**Comment by anthonycaccese** [comment]
Are you referring to these examples?
![281891733-fadfba3e-54a4-48e2-a11c-39c52797dc56](https://github.com/user-attachments/assets/e0090399-4555-41a1-9c9e-67d3237c00aa)
![281891132-e8251f3c-f033-43ed-8b55-f3a93c28131a](https://github.com/user-attachments/assets/43affab3-2213-485a-9909-9748e77e06ce)

If yes then you can achieve these by following the scraping recommendations in the readme and then setting the game art in theme settings to "Image (Cropped)"
