### ISSUE TITLE
atarijaguarcd.svg shows in black color

### ISSUE THREAD

**Issue by rogs123** [anthonycaccese/art-book-next-es#22]
Hi - running Batocera v40 on Steam Deck with art book next theme. The atarijaguarcd.svg logo displays in black color instead of white. As always, thanks for the theme.

**Comment by anthonycaccese** [comment]
thank you for finding this, I just pushed a fix that should hopefully address it.

**Comment by rogs123** [comment]
Works great!On Oct 22, 2024, at 9:52 AM, anthonycaccese ***@***.***> wrote:﻿
thank you for finding this, I just pushed a fix that should hopefully address it.
