### ISSUE TITLE
customizations not working 

### ISSUE THREAD

**Issue by mousemat86** [anthonycaccese/art-book-next-es#8]
hello – I'm fairly sure I've set this up correcty after closely following instructions but custom backgrounds aren't loading on my batocera setup. 

is there an issue with the paths in the theme? 

<img width="957" alt="Screenshot 2023-12-07 at 12 15 35" src="https://github.com/anthonycaccese/art-book-next-es/assets/57290277/ef6ad8d0-3b0b-46ba-8c9a-2ae33adb4f5e">

**Comment by anthonycaccese** [comment]
Possible to let me know which theme configuration settings you have turned on?

**Comment by mousemat86** [comment]
great thanks will give that a try - thought I was going mad!

**Comment by anthonycaccese** [comment]
will close this out for now - just reopen if you find any additional issues.
