### ISSUE TITLE
Backgrounds To Create

### ISSUE THREAD

**Issue by anthonycaccese** [anthonycaccese/art-book-next-es#9]
## Instructions
- Use one of the `system-art-mask` files from https://github.com/anthonycaccese/art-book-next-es/tree/master/resources/customizations to create act as the mask for your image
- Find a raw source gameplay image that can be scaled via nearest neighbor without artifacts
- Export your PNG at 1080px height with nearest neighbor scaling turned on.

## Systems
- [x] actionmax
- [x] amiga600
- [x] amiga1200
- [x] amiga4000
- [x] android
- [x] apfm1000
- [x] arcadia
- [x] archimedes
- [x] atarijaguarcd
- [x] atom
- [x] bbcmicro
- [x] c16
- [x] c128
- [x] camplynx
- [x] cave
- [x] cgenius
- [x] chailove
- [x] chihiro
- [x] coco
- [x] consolearcade
- [x] crvision / creativision
- [x] desktop
- [ ] dinothawr
- [x] dragon32
- [x] ecwolf
- [x] electron
- [x] emulators
- [x] epic
- [x] flash
- [x] fm7
- [x] fmtowns
- [x] fpinball
- [ ] gaelco
- [x] gamate
- [x] gamecom
- [x] gamepock
- [x] gb2players
- [x] gba2players
- [x] gbc2players
- [x] gmaster
- [x] gp32
- [ ] hbmame
- [ ] hikaru
- [x] ikemen
- [x] laser310
- [x] lcdgames
- [x] library
- [x] lutris
- [x] lutro
- [ ] love
- [ ] megadrive-msu
- [x] mess
- [x] model2
- [x] model3
- [x] msxturbor
- [x] mugen
- [x] multivision
- [x] n64dd
- [x] naomigd
- [x] naomi2
- [ ] neogeo64
- [x] neogeocdjp
- [x] ngage
- [ ] openlara
- [x] oric
- [x] palm
- [x] pcarcade
- [x] pdp1
- [ ] pinballfx
- [ ] pinballfx2
- [ ] pinballfx3
- [x] plugnplay
- [x] plus4
- [x] ps4
- [x] pyxel
- [x] retrobat
- [x] samcoupe
- [x] segastv
- [x] sgb
- [x] socrates
- [x] spectravideo
- [x] steam
- [x] superbroswar
- [x] supracan
- [x] symbian
- [x] tanodragon
- [ ] teknoparrot
- [x] thomson
- [x] ti99
- [x] to8
- [x] triforce
- [x] trs-80
- [x] tutor
- [x] tvgames
- [x] type-x
- [x] vc4000
- [x] videopacplus
- [ ] vitaquake2
- [x] windows
- [ ] zaccariapinball
- [x] zeldac
- [ ] zinc

## Auto-Collections (Genres)
- [x] auto-action
- [x] auto-adult
- [x] auto-adventure
- [x] auto-asiaticboard
- [x] auto-beatemup
- [x] auto-board
- [x] auto-breakout
- [x] auto-casino
- [x] auto-casual
- [x] auto-compilation
- [x] auto-demo
- [x] auto-educational
- [x] auto-fight
- [x] auto-huntingandfishing
- [x] auto-musicanddance
- [x] auto-pinball
- [x] auto-platform
- [x] auto-playingcards
- [x] auto-puzzle
- [x] auto-quiz
- [x] auto-racedriving
- [x] auto-reflection
- [x] auto-roleplayings
- [x] auto-shootemup
- [x] auto-shooter
- [x] auto-simulation
- [x] auto-sports
- [x] auto-sportswithanimals
- [x] auto-strategy
- [x] auto-various

**Comment by nautipuss** [comment]
Here is the first batch of backgrounds for the genre collections. They should all be pixel perfect but let me know if any need another look.

1. auto-action.png — Galaxian / Arcade

![auto-action](https://github.com/anthonycaccese/art-book-next-es/assets/274732/b1be3b8d-24f3-4d21-87da-23aa9398b2de)

2. auto-adult.png — Leisure Suit Larry / DOS

![auto-adult](https://github.com/anthonycaccese/art-book-next-es/assets/274732/fadbf8d1-b7dd-432f-8f29-fd61aa84bf0b)

3. auto-adventure.png — Castlevania Advance / GBA

![auto-adventure](https://github.com/anthonycaccese/art-book-next-es/assets/274732/d7fbd8a2-32fc-4b3f-bf56-d7ffcddcabfd)

4. auto-asiaticboard.png — Shanghai II / SNES

![auto-asiaticboard](https://github.com/anthonycaccese/art-book-next-es/assets/274732/56f4fb2e-1bb3-44b2-95db-58d4608f8206)

5. auto-beatemup.png — AvP / Arcade

![auto-beatemup](https://github.com/anthonycaccese/art-book-next-es/assets/274732/0330a986-4062-407c-8900-fe4b3a60d420)

6. auto-pinball.png — Pinball Quest / NES

![auto-pinball](https://github.com/anthonycaccese/art-book-next-es/assets/274732/86b74472-130d-4b38-9029-895de2be2097)

7. auto-platform.png — Metroid / NES

![auto-platform](https://github.com/anthonycaccese/art-book-next-es/assets/274732/1dd526fa-d884-4797-9748-b05b0af467f5)

8. auto-puzzle.png — Q*Bert / Arcade

![auto-puzzle](https://github.com/anthonycaccese/art-book-next-es/assets/274732/feaafc1a-6470-4816-9b1b-4aca7a156f50)

9. auto-racedriving.png — Driver / PSX

![auto-racedriving](https://github.com/anthonycaccese/art-book-next-es/assets/274732/8946713c-b3c8-4d85-bc9e-3a8e743167c9)

10. auto-roleplayings.png — Chrono Trigger / SNES

![auto-roleplayings](https://github.com/anthonycaccese/art-book-next-es/assets/274732/eafeca73-34ef-4cca-be86-959264e7a978)

11. auto-shooter.png — Doom / DOS

![auto-shooter](https://github.com/anthonycaccese/art-book-next-es/assets/274732/da4f7301-77e2-4c44-9726-d04fa0a8cf07)

12. auto-strategy.png — Fire Emblem / GBA

![auto-strategy](https://github.com/anthonycaccese/art-book-next-es/assets/274732/15c9baf3-b4a2-465e-9111-ec3a09bd5ce7)

Let me know what you think of them. I'll get started on the next batch.

**Comment by anthonycaccese** [comment]
These are amazing!  Thank you so much.  How would you prefer to be credited? 

something like "auto-collection genre background art created by @nautipuss"

**Comment by nautipuss** [comment]
That credit would be great, thank you!

**Comment by nautipuss** [comment]
I've got the next batch ready.

Firstly, I've replaced the auto-action image with a new one (Gauntlet / Arcade), as I want to use the Galaxian image for the auto-shootemup instead.

1. New auto-action.png — Gauntlet / Arcade

![auto-action](https://github.com/anthonycaccese/art-book-next-es/assets/274732/e4cb5128-a0ac-4e15-b089-78892adc0763)

2. auto-board.png — Art of Chess / Amiga

![auto-board](https://github.com/anthonycaccese/art-book-next-es/assets/274732/fef979fd-cfa8-4ca4-97a1-267ca7d99af5)

3. auto-breakout.png — Arkanoid / Arcade

![auto-breakout](https://github.com/anthonycaccese/art-book-next-es/assets/274732/a4d3c987-ff05-4b56-8a37-66ecc9e9e90c)

4. auto-casino.png — Caesars Palace / SNES

![auto-casino](https://github.com/anthonycaccese/art-book-next-es/assets/274732/85594629-49f9-489c-9abd-e79e30c80861)

5. auto-casual.png — Warioware Twisted / GBA

![auto-casual](https://github.com/anthonycaccese/art-book-next-es/assets/274732/eb614762-93b3-463b-9a1c-a43777422b4b)

6. auto-compilation.png — 51 Clubhouse Games / Switch

![auto-compilation](https://github.com/anthonycaccese/art-book-next-es/assets/274732/ceb0e407-dedf-4d20-ae24-8ce22020d97a)

7. auto-demo.png — Metal Gear Solid 2 / PS2

![auto-demo](https://github.com/anthonycaccese/art-book-next-es/assets/274732/e38ced47-7140-4d94-a7bc-b87aa77f6dbf)

8. auto-educational.png — Basic Math / Atari 2600

![auto-educational](https://github.com/anthonycaccese/art-book-next-es/assets/274732/856a805f-8fd3-4282-98d6-7ac2dae48096)

9. auto-fight.png — Marvel vs. Capcom Clash of Super Heroes / Arcade

![auto-fight](https://github.com/anthonycaccese/art-book-next-es/assets/274732/4f700b2b-a555-417e-951b-8de0453a3b6a)

10: auto-shootemup.png — Galaxian / Arcade (previously used for auto-action, but better for this genre)

![auto-shootemup](https://github.com/anthonycaccese/art-book-next-es/assets/274732/e080b4d6-d58d-497b-8e45-3c5cd1afcd0f)

**Comment by anthonycaccese** [comment]
Awesome, added a credit to you in each of the readme files and have started adding these to the theme.  I'll move them into the JELOS version in the next few days.  Thank you so much these look great.

**Comment by nautipuss** [comment]
Here is the final batch (minus one) of backgrounds. I've never heard of the "reflection" genre. Can you help me out? What games should it contain? It's not selecting any games from my own selection, and Google is of no help.

1. auto-huntingandfishing.png — Super Bass Fishin / SNES

![auto-huntingandfishing](https://github.com/anthonycaccese/art-book-next-es/assets/274732/a832beb0-9b80-47ae-ba8f-f0676d6f5c98)

2. auto-musicanddance.png — Dance Dance Revolution Extreme / Arcade

![auto-musicanddance](https://github.com/anthonycaccese/art-book-next-es/assets/274732/3017d579-fcea-4f8a-9ac0-799da4f78f75)

3. auto-playingcards.png — Super Solitaire / SNES

![auto-playingcards](https://github.com/anthonycaccese/art-book-next-es/assets/274732/879ca3e0-e9bb-4e25-ac99-18d79a472481)

4. auto-quiz.png — Trivial Pursuit / CD32

![auto-quiz](https://github.com/anthonycaccese/art-book-next-es/assets/274732/fb2859b9-7f7b-4e09-af62-c34ba4246e47)

5. auto-simulation.png — MS Flight Simulator / DOS

![auto-simulation](https://github.com/anthonycaccese/art-book-next-es/assets/274732/21d8b1f9-ee28-4d72-a7ad-dfa5e471bc4c)

6. auto-sports.png — California Games / Atari Lynx

![auto-sports](https://github.com/anthonycaccese/art-book-next-es/assets/274732/c5654ca3-2443-4ae2-baa0-0c643aa61918)

7. auto-sportswithanimals.png — Arlington Horse Racing / Arcade

![auto-sportswithanimals](https://github.com/anthonycaccese/art-book-next-es/assets/274732/9e811d60-791b-4edf-b3ce-cae3aaaa0496)

8. auto-various.png — Trauma Center: Under the Knife / NDS

![auto-various](https://github.com/anthonycaccese/art-book-next-es/assets/274732/31c5a442-2af3-476c-9cb8-5fca13cda126)

**Comment by getupor** [comment]
Hello
I've notice some missing systems for RetroBat.
[RetrobatMissingSystems.txt](https://github.com/anthonycaccese/art-book-next-es/files/13641029/RetrobatMissingSystems.txt)

**Comment by anthonycaccese** [comment]
@nautipuss it looks like puzzle bobble would be considered a reflection game.   I did a search for that genre on screenscraper and that came up so I went with it =)

![auto-reflection](https://github.com/anthonycaccese/art-book-next-es/assets/1454947/0bd3a47c-e797-4cc9-8ceb-6025de8f27be)

Let me know what you think.  Also wanted to get your opinion of the existing auto-allgames and custom-collection images.  was trying to think of a classic pixel based game with a library of some kind.

**Comment by anthonycaccese** [comment]
thank you @getupor if you have recommendations of popular games for each of those systems that will be a great help to me (it helps save research time trying to find an appropriate game to pull a screenshot from)

**Comment by nautipuss** [comment]
@anthonycaccese That reflection image works well, I never thought of trying Screenscraper for info.

As for classic games with libraries, the first that popped into my head was the point-and-click Discworld games:

![library-1](https://github.com/anthonycaccese/art-book-next-es/assets/274732/c96c599b-0a16-4729-ae9f-fde3aa34ea9e)

Also, Stardew Valley has a library, and the pixel crop looks great:

![library-2](https://github.com/anthonycaccese/art-book-next-es/assets/274732/ac53aa79-6774-48b7-a337-e74c1a47165f)

I'll let you know if I come up with any others.

**Comment by anthonycaccese** [comment]
@nautipuss thank you for your work on this - I just added the genre art to the root JELOS theme as well so after the next release your images will be part of that.

**Comment by nautipuss** [comment]
@anthonycaccese No problem! Happy to get involved.
